### ISSUE TITLE
Some encounters are split before the end of the encounter (Igrexion)

### ISSUE THREAD

**Issue by omonoiatis9** [shalzuth/LostArkLogger#55]
I noticed that a few seconds before igrexion dies, the meters reset on their own and then are repopulated (only by the top damage dealer). Going to the encounters section it seems that the current session was split in 2 a few seconds earlier before the boss died, resulting in some of the dmg being left out of the correct session. The encounter should end only after the boss dies.

Didn't test in other guardians to see if this happens only with Igrexion or all encounters.
EDIT: Most likely happens everywhere, tested with Velganos too. Same issue

**Comment by noita-player** [comment]
this is most likely 69f2a551f08f1bd58254660f457d30adb903f710

**Comment by perks** [comment]
Can confirm, this bug happens when:

`OpCodes.PKTRaidBossKillNotify` comes in first
then
a damage packet is processed `PKTSkillDamageNotify`

then finally

`OpCodes.PKTRaidResult`

at least this is the order in Guardian Raids. Willing to submit a PR that maybe does some logic checks on npc entity ID? We shouldn't get Raid Result until Argos end I think. Have no more Argos lockouts though so cannot test this until reset
